### ISSUE TITLE
Twitter link broken on Android

### ISSUE THREAD

**Issue by xballoy** [MielPoPSCrew/DevoxxFR-2018-PWA#15]
Hello,

The Twitter links are in form https://twitter.com/**@xavierballoy**. This link is working on desktop but not on mobile with the Twitter app installed (on Android, I couldn't test on iOS).
On Android the app says: "User not found".

However the link https://twitter.com/**xavierballoy** is working (on desktop AND mobile)

Maybe we should check if the Twitter handle starts with "@" and remove it.

What do you think?

**Comment by leodonny** [comment]
Hello !
Indeed we tried on desktop and nothing went wrong, I will remove the "@".

There is another issue on twitter links, for some speakers the API returns us full links (example : "https://twitter.com/@xavierballoy"). 

I will try to fix it quickly.
